server:
  port: 8088



spring:
  datasource:                                           # 数据源的相关配置
      url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      password: rootpwd
  redis:
    database: 1
    sentinel:
      master: imooc-master
      nodes: 192.168.5.205:26379,192.168.5.206:26379,192.168.5.207:26379
    password: imooc
    # Redis 单机单实例
#    database: 1
#    host: 192.168.5.205
#    port: 6379
#    password: imooc
    # Redis 哨兵



mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl