server:
  port: 80

spring:
  datasource:                                           # 数据源的相关配置
      url: jdbc:mysql://192.168.5.201:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      password: root